{% set name = "python-tsp" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python_tsp-{{ version }}.tar.gz
  sha256: 3e99a8f817d582fb4883d9a10d05f6f458b387c8f921b2e2fb63021777a1656a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.8
    - tsplib95 >=0.7.1
    - requests >=2.28.0
    - numpy >=1.23.5

test:
  imports:
    - python_tsp
  files:
    - example.py
    - a280.tsp
  commands:
    - python example.py
  requires:
    - pip

about:
  home: https://github.com/fillipe-gsm/python-tsp
  summary: Library to solve the Traveling Salesperson Problem in pure Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
